[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
goaldrop = "2NUW8WnPJpsSruWhQ5as8AeynBDdfhth5YBXpFWfxZnc"

[programs.devnet]
goaldrop = "2NUW8WnPJpsSruWhQ5as8AeynBDdfhth5YBXpFWfxZnc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test:anchor"

[test]
startup_wait = 10000
